services:
  - type: web
    name: medication-reminder
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: ROLLUP_SKIP_NODEJS_NATIVE
        value: 1
      - key: ESBUILD_BINARY_PATH
        value: /tmp/esbuild
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
      - key: SKIP_OPTIONAL_DEPENDENCIES
        value: true
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - client/**
        - server/**
        - shared/**
        - render-build.sh
        - render.yaml
        - .npmrc
    plan: free